---
- hosts: all
  become: yes
  var:
    commmon: this is my own veriblwe
  tasks:
  - name: ping all
    ping:
  - name: print defsult  variblee 
    debug:
      msg: " os family is {{ansible_os_family}}"

  - name: print my own varible
    debug:
      msg: " {{commmon}}"

  - name: pring group varibles
    debug:
      msg: " group {{commmon}}"

  - name: host varibles
    debug:
      msg: " host {{commmon}}"